version: '3'
services:
  ide:
    image: ${IMAGE}:${ENV}
    build:
      context: .
      args:
        USER: ${USER}
        EMAIL: ${EMAIL}
        ENV: ${ENV}
        IMAGE: ${IMAGE}
        DOMAIN: ${DOMAIN}
        IDE_LANG: ${IDE_LANG}
    container_name: ide
    restart: on-failure
    environment:
      - USER=${USER}
      - EMAIL=${EMAIL}
      - IMAGE=${IMAGE}
      - ENV=${ENV}
      - DOMAIN=${DOMAIN}
      - IDE_LANG=${IDE_LANG}
    ports:
      - "8443:8443"
    networks:
      - internal
    volumes:
      - ${HOME}/go/src/github.com/${USER}:${HOME}/project:cached
      - ${HOME}/.ssh:${HOME}/.ssh:cached
      - ${HOME}/.local/share/code-server:${HOME}/.local/share/code-server:cached
networks:
  internal:
    external: false
