version: '3'
services:
  ide:
    image: ${IMAGE}:${ENV}
    build:
      context: .
      args:
        USER: ${USER}
        EMAIL: ${EMAIL}
        ENV: ${ENV}
        IMAGE: ${IMAGE}
        DOMAIN: ${DOMAIN}
        IDE_LANG: ${IDE_LANG}
    container_name: ide
    restart: on-failure
    environment:
      - USER=${USER}
      - EMAIL=${EMAIL}
      - IMAGE=${IMAGE}
      - ENV=${ENV}
      - DOMAIN=${DOMAIN}
      - IDE_LANG=${IDE_LANG}
    networks:
      - internal
      - traefik-public
    volumes:
      - ${HOME}/go/src/github.com/${USER}:${HOME}/project:cached
      - ${HOME}/.ssh:${HOME}/.ssh:cached
      - ${HOME}/.local/share/code-server:${HOME}/.local/share/code-server:cached
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.backend=${USER}
        - traefik.frontend.rule=Host:${DOMAIN}
        - traefik.docker.network=traefik-public
        - traefik.enable=true
        - traefik.port=8443
        - traefik.tags=traefik-public
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https

networks:
  traefik-public:
    external: true
  internal:
    external: false