version: '3.8'
services:
  ide:
    image: ${IMAGE}
    build:
      context: .
      args:
        USER: ${USER}
        EMAIL: ${EMAIL}
        ENV: ${ENV}
        IMAGE: ${IMAGE}
        DOMAIN: ${DOMAIN}
        IDE_LANG: ${IDE_LANG}
        IDE_ROOT: ${IDE_ROOT}
        PROJ_HOME: ${PROJ_HOME}
        SSH_DIR: ${SSH_DIR}
        CODE_SERVER_FILES: ${CODE_SERVER_FILES}
    container_name: ${USER}-ide
    restart: on-failure
    environment:
      - USER=${USER}
      - EMAIL=${EMAIL}
      - IMAGE=${IMAGE}
      - ENV=${ENV}
      - DOMAIN=${DOMAIN}
      - IDE_LANG=${IDE_LANG}
      - IDE_ROOT=${IDE_ROOT}
      - PROJ_HOME=${PROJ_HOME}
      - SSH_DIR=${SSH_DIR}
      - CODE_SERVER_FILES=${CODE_SERVER_FILES}
    ports:
      - "8443:8443"
    networks:
      - internal
    volumes:
      - ${PROJ_HOME}:/home/${USER}/project:cached
      - ${SSH_DIR}:/home/${USER}/.ssh:cached
      - ${CODE_SERVER_FILES}:/home/${USER}/.local/share/code-server:cached
networks:
  internal:
    external: false
