version: '3'
services:
  ide:
    image: ${IMAGE}
    build:
      context: .
      args:
        USER: ${USER}
        EMAIL: ${EMAIL}
    container_name: ide
    restart: on-failure
    environment:
      - USER=${USER}
      - EMAIL=${EMAIL}
    env_file: .env
    ports:
      - "8443:8443"
    networks:
      - internal
    volumes:
      - ${HOME}/projects:/home/${USER}/projects:cached
      - ${HOME}/.ssh:/home/${USER}/.ssh:cached
      - ${HOME}/.local/share/code-server:/home/${USER}/.local/share/code-server:cached
networks:
  internal:
    external: false
