name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches: [main]
  # run it during pull request
  pull_request:

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    env:
      USER: ${{ secrets.USER }}
      EMAIL: ${{ secrets.EMAIL }}
      IDE_LANG: ${{ secrets.IDE_LANG }}
      IMAGE: ${{ secrets.IMAGE }}
      ENV: ${{ secrets.ENV }}

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: basic build
        run: |
          docker build --build-arg USER=${USER} --build-arg EMAIL=${EMAIL} --build-arg IDE_LANG=${IDE_LANG} -t ${IMAGE}:${ENV} .
          docker push ${IMAGE}:${ENV}
  